In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.svm import SVC

from xgboost import XGBClassifier

In [2]:
data=pd.read_csv("new_updated_coordinate.csv")
data1=pd.read_csv('alsecure_final_test.csv')
data

pgNo  startX   startY    endX     endY       w      h  fntSize  \
0        1   74.85    69.78  158.84    80.26   83.99  10.48  14.6832   
1        1  163.85    69.78  175.59    80.26   11.74  10.48  14.6832   
2        1  180.53    69.78  283.82    80.26  103.29  10.48  14.6832   
3        1  288.77    69.78  368.10    80.26   79.33  10.48  14.6832   
4        1  378.07    69.78  432.12    80.26   54.05  10.48  14.6832   
...    ...     ...      ...     ...      ...     ...    ...      ...   
1982     1  395.44  1515.38  438.81  1521.02   43.37   5.64   9.7500   
1983     1  441.52  1515.38  460.49  1521.02   18.97   5.64   9.7500   
1984     1  463.20  1515.38  494.62  1521.02   31.42   5.64   9.7500   
1985     1  497.33  1515.38  540.70  1521.02   43.37   5.64   9.7500   
1986     1  543.41  1515.38  633.34  1521.02   89.93   5.64   9.7500   

      txtColor                txtFnt  ... top_txtColor  top_txtFnt  \
0    -16777216  BookmanOldStyle-Bold  ...          NaN         NaN   
1    -16777216  BookmanOldStyle-Bold  ...          NaN         NaN   
2    -16777216  BookmanOldStyle-Bold  ...          NaN         NaN   
3    -16777216  BookmanOldStyle-Bold  ...          NaN         NaN   
4    -16777216  BookmanOldStyle-Bold  ...          NaN         NaN   
...        ...                   ...  ...          ...         ...   
1982 -16777216             Helvetica  ...          NaN         NaN   
1983 -16777216             Helvetica  ...          NaN         NaN   
1984 -16777216             Helvetica  ...          NaN         NaN   
1985 -16777216             Helvetica  ...          NaN         NaN   
1986 -16777216             Helvetica  ...          NaN         NaN   

      top_topMargin  top_bottomMargin  top_leftMargin  top_rightMargin  \
0               NaN               NaN             NaN              NaN   
1               NaN               NaN             NaN              NaN   
2               NaN               NaN             NaN              NaN   
3               NaN               NaN             NaN              NaN   
4               NaN               NaN             NaN              NaN   
...             ...               ...             ...              ...   
1982            NaN               NaN             NaN              NaN   
1983            NaN               NaN             NaN              NaN   
1984            NaN               NaN             NaN              NaN   
1985            NaN               NaN             NaN              NaN   
1986            NaN               NaN             NaN              NaN   

      top_wordPosition  top_txt                txt  label  
0                  NaN      NaN           ALSECURE   Name  
1                  NaN      NaN                  &   Name  
2                  NaN      NaN         PROTECTION   Name  
3                  NaN      NaN           SERVICES   Name  
4                  NaN      NaN            (INDIA)   Name  
...                ...      ...                ...    ...  
1982               NaN      NaN           68243000    NaN  
1983               NaN      NaN               Fax:    NaN  
1984               NaN      NaN            (91-80)    NaN  
1985               NaN      NaN           68243001    NaN  
1986               NaN      NaN  www.teamlease.com    NaN  

[1987 rows x 83 columns]

In [3]:
data1.shape

(621, 83)

In [4]:
data.shape

(1987, 83)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1987 entries, 0 to 1986
Data columns (total 83 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   pgNo                 1987 non-null   int64  
 1   startX               1987 non-null   float64
 2   startY               1987 non-null   float64
 3   endX                 1987 non-null   float64
 4   endY                 1987 non-null   float64
 5   w                    1987 non-null   float64
 6   h                    1987 non-null   float64
 7   fntSize              1987 non-null   float64
 8   txtColor             1987 non-null   int64  
 9   txtFnt               1987 non-null   object 
 10  docName              1987 non-null   object 
 11  pgW                  1987 non-null   int64  
 12  pgH                  1987 non-null   int64  
 13  topMargin            1987 non-null   float64
 14  bottomMargin         1987 non-null   float64
 15  leftMargin           1987 non-null   f

In [6]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 621 entries, 0 to 620
Data columns (total 83 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   pgNo                 621 non-null    int64  
 1   startX               621 non-null    float64
 2   startY               621 non-null    float64
 3   endX                 621 non-null    float64
 4   endY                 621 non-null    float64
 5   w                    621 non-null    float64
 6   h                    621 non-null    float64
 7   fntSize              621 non-null    float64
 8   txtColor             621 non-null    int64  
 9   txtFnt               621 non-null    object 
 10  docName              621 non-null    object 
 11  pgW                  621 non-null    int64  
 12  pgH                  621 non-null    int64  
 13  topMargin            621 non-null    float64
 14  bottomMargin         621 non-null    float64
 15  leftMargin           621 non-null    flo

In [7]:
data['startX']=data['startX'].apply(np.floor)
data1['startX']=data['startX'].apply(np.floor)


In [8]:
data

pgNo  startX   startY    endX     endY       w      h  fntSize  \
0        1    74.0    69.78  158.84    80.26   83.99  10.48  14.6832   
1        1   163.0    69.78  175.59    80.26   11.74  10.48  14.6832   
2        1   180.0    69.78  283.82    80.26  103.29  10.48  14.6832   
3        1   288.0    69.78  368.10    80.26   79.33  10.48  14.6832   
4        1   378.0    69.78  432.12    80.26   54.05  10.48  14.6832   
...    ...     ...      ...     ...      ...     ...    ...      ...   
1982     1   395.0  1515.38  438.81  1521.02   43.37   5.64   9.7500   
1983     1   441.0  1515.38  460.49  1521.02   18.97   5.64   9.7500   
1984     1   463.0  1515.38  494.62  1521.02   31.42   5.64   9.7500   
1985     1   497.0  1515.38  540.70  1521.02   43.37   5.64   9.7500   
1986     1   543.0  1515.38  633.34  1521.02   89.93   5.64   9.7500   

      txtColor                txtFnt  ... top_txtColor  top_txtFnt  \
0    -16777216  BookmanOldStyle-Bold  ...          NaN         NaN   
1    -16777216  BookmanOldStyle-Bold  ...          NaN         NaN   
2    -16777216  BookmanOldStyle-Bold  ...          NaN         NaN   
3    -16777216  BookmanOldStyle-Bold  ...          NaN         NaN   
4    -16777216  BookmanOldStyle-Bold  ...          NaN         NaN   
...        ...                   ...  ...          ...         ...   
1982 -16777216             Helvetica  ...          NaN         NaN   
1983 -16777216             Helvetica  ...          NaN         NaN   
1984 -16777216             Helvetica  ...          NaN         NaN   
1985 -16777216             Helvetica  ...          NaN         NaN   
1986 -16777216             Helvetica  ...          NaN         NaN   

      top_topMargin  top_bottomMargin  top_leftMargin  top_rightMargin  \
0               NaN               NaN             NaN              NaN   
1               NaN               NaN             NaN              NaN   
2               NaN               NaN             NaN              NaN   
3               NaN               NaN             NaN              NaN   
4               NaN               NaN             NaN              NaN   
...             ...               ...             ...              ...   
1982            NaN               NaN             NaN              NaN   
1983            NaN               NaN             NaN              NaN   
1984            NaN               NaN             NaN              NaN   
1985            NaN               NaN             NaN              NaN   
1986            NaN               NaN             NaN              NaN   

      top_wordPosition  top_txt                txt  label  
0                  NaN      NaN           ALSECURE   Name  
1                  NaN      NaN                  &   Name  
2                  NaN      NaN         PROTECTION   Name  
3                  NaN      NaN           SERVICES   Name  
4                  NaN      NaN            (INDIA)   Name  
...                ...      ...                ...    ...  
1982               NaN      NaN           68243000    NaN  
1983               NaN      NaN               Fax:    NaN  
1984               NaN      NaN            (91-80)    NaN  
1985               NaN      NaN           68243001    NaN  
1986               NaN      NaN  www.teamlease.com    NaN  

[1987 rows x 83 columns]

In [9]:
data['endX']=data['endX'].apply(np.ceil)
data1['endX']=data['endX'].apply(np.ceil)

In [10]:
data['w']=data['endX']-data['startX']
data1['w']=data['endX']-data['startX']

data

pgNo  startX   startY   endX     endY      w      h  fntSize  txtColor  \
0        1    74.0    69.78  159.0    80.26   85.0  10.48  14.6832 -16777216   
1        1   163.0    69.78  176.0    80.26   13.0  10.48  14.6832 -16777216   
2        1   180.0    69.78  284.0    80.26  104.0  10.48  14.6832 -16777216   
3        1   288.0    69.78  369.0    80.26   81.0  10.48  14.6832 -16777216   
4        1   378.0    69.78  433.0    80.26   55.0  10.48  14.6832 -16777216   
...    ...     ...      ...    ...      ...    ...    ...      ...       ...   
1982     1   395.0  1515.38  439.0  1521.02   44.0   5.64   9.7500 -16777216   
1983     1   441.0  1515.38  461.0  1521.02   20.0   5.64   9.7500 -16777216   
1984     1   463.0  1515.38  495.0  1521.02   32.0   5.64   9.7500 -16777216   
1985     1   497.0  1515.38  541.0  1521.02   44.0   5.64   9.7500 -16777216   
1986     1   543.0  1515.38  634.0  1521.02   91.0   5.64   9.7500 -16777216   

                    txtFnt  ... top_txtColor  top_txtFnt  top_topMargin  \
0     BookmanOldStyle-Bold  ...          NaN         NaN            NaN   
1     BookmanOldStyle-Bold  ...          NaN         NaN            NaN   
2     BookmanOldStyle-Bold  ...          NaN         NaN            NaN   
3     BookmanOldStyle-Bold  ...          NaN         NaN            NaN   
4     BookmanOldStyle-Bold  ...          NaN         NaN            NaN   
...                    ...  ...          ...         ...            ...   
1982             Helvetica  ...          NaN         NaN            NaN   
1983             Helvetica  ...          NaN         NaN            NaN   
1984             Helvetica  ...          NaN         NaN            NaN   
1985             Helvetica  ...          NaN         NaN            NaN   
1986             Helvetica  ...          NaN         NaN            NaN   

      top_bottomMargin  top_leftMargin  top_rightMargin  top_wordPosition  \
0                  NaN             NaN              NaN               NaN   
1                  NaN             NaN              NaN               NaN   
2                  NaN             NaN              NaN               NaN   
3                  NaN             NaN              NaN               NaN   
4                  NaN             NaN              NaN               NaN   
...                ...             ...              ...               ...   
1982               NaN             NaN              NaN               NaN   
1983               NaN             NaN              NaN               NaN   
1984               NaN             NaN              NaN               NaN   
1985               NaN             NaN              NaN               NaN   
1986               NaN             NaN              NaN               NaN   

      top_txt                txt  label  
0         NaN           ALSECURE   Name  
1         NaN                  &   Name  
2         NaN         PROTECTION   Name  
3         NaN           SERVICES   Name  
4         NaN            (INDIA)   Name  
...       ...                ...    ...  
1982      NaN           68243000    NaN  
1983      NaN               Fax:    NaN  
1984      NaN            (91-80)    NaN  
1985      NaN           68243001    NaN  
1986      NaN  www.teamlease.com    NaN  

[1987 rows x 83 columns]

In [11]:
data.loc[data['txtColor'] == (-16777216), 'txtColor'] = 1
data1.loc[data['txtColor'] == (-16777216), 'txtColor'] = 1

In [12]:
data['label'] = data['label'].fillna('unnamed')
data1['label'] = data['label'].fillna('unnamed')

In [13]:
data

pgNo  startX   startY   endX     endY      w      h  fntSize  txtColor  \
0        1    74.0    69.78  159.0    80.26   85.0  10.48  14.6832         1   
1        1   163.0    69.78  176.0    80.26   13.0  10.48  14.6832         1   
2        1   180.0    69.78  284.0    80.26  104.0  10.48  14.6832         1   
3        1   288.0    69.78  369.0    80.26   81.0  10.48  14.6832         1   
4        1   378.0    69.78  433.0    80.26   55.0  10.48  14.6832         1   
...    ...     ...      ...    ...      ...    ...    ...      ...       ...   
1982     1   395.0  1515.38  439.0  1521.02   44.0   5.64   9.7500         1   
1983     1   441.0  1515.38  461.0  1521.02   20.0   5.64   9.7500         1   
1984     1   463.0  1515.38  495.0  1521.02   32.0   5.64   9.7500         1   
1985     1   497.0  1515.38  541.0  1521.02   44.0   5.64   9.7500         1   
1986     1   543.0  1515.38  634.0  1521.02   91.0   5.64   9.7500         1   

                    txtFnt  ... top_txtColor  top_txtFnt  top_topMargin  \
0     BookmanOldStyle-Bold  ...          NaN         NaN            NaN   
1     BookmanOldStyle-Bold  ...          NaN         NaN            NaN   
2     BookmanOldStyle-Bold  ...          NaN         NaN            NaN   
3     BookmanOldStyle-Bold  ...          NaN         NaN            NaN   
4     BookmanOldStyle-Bold  ...          NaN         NaN            NaN   
...                    ...  ...          ...         ...            ...   
1982             Helvetica  ...          NaN         NaN            NaN   
1983             Helvetica  ...          NaN         NaN            NaN   
1984             Helvetica  ...          NaN         NaN            NaN   
1985             Helvetica  ...          NaN         NaN            NaN   
1986             Helvetica  ...          NaN         NaN            NaN   

      top_bottomMargin  top_leftMargin  top_rightMargin  top_wordPosition  \
0                  NaN             NaN              NaN               NaN   
1                  NaN             NaN              NaN               NaN   
2                  NaN             NaN              NaN               NaN   
3                  NaN             NaN              NaN               NaN   
4                  NaN             NaN              NaN               NaN   
...                ...             ...              ...               ...   
1982               NaN             NaN              NaN               NaN   
1983               NaN             NaN              NaN               NaN   
1984               NaN             NaN              NaN               NaN   
1985               NaN             NaN              NaN               NaN   
1986               NaN             NaN              NaN               NaN   

      top_txt                txt    label  
0         NaN           ALSECURE     Name  
1         NaN                  &     Name  
2         NaN         PROTECTION     Name  
3         NaN           SERVICES     Name  
4         NaN            (INDIA)     Name  
...       ...                ...      ...  
1982      NaN           68243000  unnamed  
1983      NaN               Fax:  unnamed  
1984      NaN            (91-80)  unnamed  
1985      NaN           68243001  unnamed  
1986      NaN  www.teamlease.com  unnamed  

[1987 rows x 83 columns]

In [14]:
data.drop('txt',inplace=True,axis=1)
data1.drop('txt',inplace=True,axis=1)

In [15]:
#to temporary purpose dropping column txtFnt
data.drop('txtFnt',inplace=True,axis=1)
data1.drop('txtFnt',inplace=True,axis=1)

In [16]:
data.shape

(1987, 81)

In [17]:
data.drop('docName',inplace=True,axis=1)
data1.drop('docName',inplace=True,axis=1)


In [18]:
data.shape

(1987, 80)

In [19]:
data.drop('top_txt',inplace=True,axis=1)
data.drop('bottom_txt',inplace=True,axis=1)
data.drop('right_txt',inplace=True,axis=1)
data.drop('left_txt',inplace=True,axis=1)




data.drop('top_txtColor',inplace=True,axis=1)
data.drop('top_txtFnt',inplace=True,axis=1)
data.drop('top_fntSize',inplace=True,axis=1)
data.drop('bottom_txtColor',inplace=True,axis=1)
data.drop('bottom_txtFnt',inplace=True,axis=1)
data.drop('bottom_fntSize',inplace=True,axis=1)
data.drop('right_txtColor',inplace=True,axis=1)
data.drop('right_txtFnt',inplace=True,axis=1)
data.drop('right_fntSize',inplace=True,axis=1)
data.drop('left_txtColor',inplace=True,axis=1)
data.drop('left_txtFnt',inplace=True,axis=1)
data.drop('left_fntSize',inplace=True,axis=1)



data1.drop('top_txt',inplace=True,axis=1)
data1.drop('bottom_txt',inplace=True,axis=1)
data1.drop('right_txt',inplace=True,axis=1)
data1.drop('left_txt',inplace=True,axis=1)


data1.drop('top_txtColor',inplace=True,axis=1)
data1.drop('top_txtFnt',inplace=True,axis=1)
data1.drop('top_fntSize',inplace=True,axis=1)
data1.drop('bottom_txtColor',inplace=True,axis=1)
data1.drop('bottom_txtFnt',inplace=True,axis=1)
data1.drop('bottom_fntSize',inplace=True,axis=1)
data1.drop('right_txtColor',inplace=True,axis=1)
data1.drop('right_txtFnt',inplace=True,axis=1)
data1.drop('right_fntSize',inplace=True,axis=1)
data1.drop('left_txtColor',inplace=True,axis=1)
data1.drop('left_txtFnt',inplace=True,axis=1)
data1.drop('left_fntSize',inplace=True,axis=1)

In [20]:
data['top_wordPosition'] = data['top_wordPosition'].fillna(0)
data['top_rightMargin'] = data['top_rightMargin'].fillna(0)
data['top_leftMargin'] = data['top_leftMargin'].fillna(0)
data['top_bottomMargin'] = data['top_bottomMargin'].fillna(0)
data['top_topMargin'] = data['top_topMargin'].fillna(0)
data['top_h'] = data['top_h'].fillna(0)
data['top_w'] = data['top_w'].fillna(0)
data['top_endY'] = data['top_endY'].fillna(0)
data['top_endX'] = data['top_endX'].fillna(0)
data['top_startY'] = data['top_startY'].fillna(0)
data['top_startX'] = data['top_startX'].fillna(0)
data['bottom_wordPosition'] = data['bottom_wordPosition'].fillna(0)
data['bottom_rightMargin'] = data['bottom_rightMargin'].fillna(0)
data['bottom_leftMargin'] = data['bottom_leftMargin'].fillna(0)
data['bottom_bottomMargin'] = data['bottom_bottomMargin'].fillna(0)
data['bottom_topMargin'] = data['bottom_topMargin'].fillna(0)
data['bottom_h'] = data['bottom_h'].fillna(0)
data['bottom_w'] = data['bottom_w'].fillna(0)
data['bottom_endY'] = data['bottom_endY'].fillna(0)
data['bottom_endX'] = data['bottom_endX'].fillna(0)
data['bottom_startY'] = data['bottom_startY'].fillna(0)
data['bottom_startX'] = data['bottom_startX'].fillna(0)
data['right_wordPosition'] = data['right_wordPosition'].fillna(0)
data['right_rightMargin'] = data['right_rightMargin'].fillna(0)
data['right_leftMargin'] = data['right_leftMargin'].fillna(0)
data['right_bottomMargin'] = data['right_bottomMargin'].fillna(0)
data['right_topMargin'] = data['right_topMargin'].fillna(0)
data['right_h'] = data['right_h'].fillna(0)
data['right_w'] = data['right_w'].fillna(0)
data['right_endY'] = data['right_endY'].fillna(0)
data['right_endX'] = data['right_endX'].fillna(0)
data['right_startY'] = data['right_startY'].fillna(0)
data['right_startX'] = data['right_startX'].fillna(0)
data['left_wordPosition'] = data['left_wordPosition'].fillna(0)
data['left_rightMargin'] = data['left_rightMargin'].fillna(0)
data['left_leftMargin'] = data['left_leftMargin'].fillna(0)
data['left_bottomMargin'] = data['left_bottomMargin'].fillna(0)
data['left_topMargin'] = data['left_topMargin'].fillna(0)
data['left_h'] = data['left_h'].fillna(0)
data['left_w'] = data['left_w'].fillna(0)
data['left_endY'] = data['left_endY'].fillna(0)
data['left_endX'] = data['left_endX'].fillna(0)
data['left_startY'] = data['left_startY'].fillna(0)
data['left_startX'] = data['left_startX'].fillna(0)






data1['top_wordPosition'] = data['top_wordPosition'].fillna(0)
data1['top_rightMargin'] = data['top_rightMargin'].fillna(0)
data1['top_leftMargin'] = data['top_leftMargin'].fillna(0)
data1['top_bottomMargin'] = data['top_bottomMargin'].fillna(0)
data1['top_topMargin'] = data['top_topMargin'].fillna(0)
data1['top_h'] = data['top_h'].fillna(0)
data1['top_w'] = data['top_w'].fillna(0)
data1['top_endY'] = data['top_endY'].fillna(0)
data1['top_endX'] = data['top_endX'].fillna(0)
data1['top_startY'] = data['top_startY'].fillna(0)
data1['top_startX'] = data['top_startX'].fillna(0)
data1['bottom_wordPosition'] = data['bottom_wordPosition'].fillna(0)
data1['bottom_rightMargin'] = data['bottom_rightMargin'].fillna(0)
data1['bottom_leftMargin'] = data['bottom_leftMargin'].fillna(0)
data1['bottom_bottomMargin'] = data['bottom_bottomMargin'].fillna(0)
data1['bottom_topMargin'] = data['bottom_topMargin'].fillna(0)
data1['bottom_h'] = data['bottom_h'].fillna(0)
data1['bottom_w'] = data['bottom_w'].fillna(0)
data1['bottom_endY'] = data['bottom_endY'].fillna(0)
data1['bottom_endX'] = data['bottom_endX'].fillna(0)
data1['bottom_startY'] = data['bottom_startY'].fillna(0)
data1['bottom_startX'] = data['bottom_startX'].fillna(0)
data1['right_wordPosition'] = data['right_wordPosition'].fillna(0)
data1['right_rightMargin'] = data['right_rightMargin'].fillna(0)
data1['right_leftMargin'] = data['right_leftMargin'].fillna(0)
data1['right_bottomMargin'] = data['right_bottomMargin'].fillna(0)
data1['right_topMargin'] = data['right_topMargin'].fillna(0)
data1['right_h'] = data['right_h'].fillna(0)
data1['right_w'] = data['right_w'].fillna(0)
data1['right_endY'] = data['right_endY'].fillna(0)
data1['right_endX'] = data['right_endX'].fillna(0)
data1['right_startY'] = data['right_startY'].fillna(0)
data1['right_startX'] = data['right_startX'].fillna(0)
data1['left_wordPosition'] = data['left_wordPosition'].fillna(0)
data1['left_rightMargin'] = data['left_rightMargin'].fillna(0)
data1['left_leftMargin'] = data['left_leftMargin'].fillna(0)
data1['left_bottomMargin'] = data['left_bottomMargin'].fillna(0)
data1['left_topMargin'] = data['left_topMargin'].fillna(0)
data1['left_h'] = data['left_h'].fillna(0)
data1['left_w'] = data['left_w'].fillna(0)
data1['left_endY'] = data['left_endY'].fillna(0)
data1['left_endX'] = data['left_endX'].fillna(0)
data1['left_startY'] = data['left_startY'].fillna(0)
data1['left_startX'] = data['left_startX'].fillna(0)










In [21]:
#data.drop['top_txt',inplace=True,axis=1]
data

pgNo  startX   startY   endX     endY      w      h  fntSize  txtColor  \
0        1    74.0    69.78  159.0    80.26   85.0  10.48  14.6832         1   
1        1   163.0    69.78  176.0    80.26   13.0  10.48  14.6832         1   
2        1   180.0    69.78  284.0    80.26  104.0  10.48  14.6832         1   
3        1   288.0    69.78  369.0    80.26   81.0  10.48  14.6832         1   
4        1   378.0    69.78  433.0    80.26   55.0  10.48  14.6832         1   
...    ...     ...      ...    ...      ...    ...    ...      ...       ...   
1982     1   395.0  1515.38  439.0  1521.02   44.0   5.64   9.7500         1   
1983     1   441.0  1515.38  461.0  1521.02   20.0   5.64   9.7500         1   
1984     1   463.0  1515.38  495.0  1521.02   32.0   5.64   9.7500         1   
1985     1   497.0  1515.38  541.0  1521.02   44.0   5.64   9.7500         1   
1986     1   543.0  1515.38  634.0  1521.02   91.0   5.64   9.7500         1   

       pgW  ...  top_endX  top_endY  top_w  top_h  top_topMargin  \
0      612  ...       0.0       0.0    0.0    0.0            0.0   
1      612  ...       0.0       0.0    0.0    0.0            0.0   
2      612  ...       0.0       0.0    0.0    0.0            0.0   
3      612  ...       0.0       0.0    0.0    0.0            0.0   
4      612  ...       0.0       0.0    0.0    0.0            0.0   
...    ...  ...       ...       ...    ...    ...            ...   
1982  1191  ...       0.0       0.0    0.0    0.0            0.0   
1983  1191  ...       0.0       0.0    0.0    0.0            0.0   
1984  1191  ...       0.0       0.0    0.0    0.0            0.0   
1985  1191  ...       0.0       0.0    0.0    0.0            0.0   
1986  1191  ...       0.0       0.0    0.0    0.0            0.0   

      top_bottomMargin  top_leftMargin  top_rightMargin  top_wordPosition  \
0                  0.0             0.0              0.0               0.0   
1                  0.0             0.0              0.0               0.0   
2                  0.0             0.0              0.0               0.0   
3                  0.0             0.0              0.0               0.0   
4                  0.0             0.0              0.0               0.0   
...                ...             ...              ...               ...   
1982               0.0             0.0              0.0               0.0   
1983               0.0             0.0              0.0               0.0   
1984               0.0             0.0              0.0               0.0   
1985               0.0             0.0              0.0               0.0   
1986               0.0             0.0              0.0               0.0   

        label  
0        Name  
1        Name  
2        Name  
3        Name  
4        Name  
...       ...  
1982  unnamed  
1983  unnamed  
1984  unnamed  
1985  unnamed  
1986  unnamed  

[1987 rows x 64 columns]

In [22]:
data.shape

(1987, 64)

In [23]:
data1.shape

(621, 64)

In [24]:
data.iloc[:,9].values

array([ 612,  612,  612, ..., 1191, 1191, 1191])

In [25]:
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

In [26]:
test_data=data1.iloc[:,:-1]

In [27]:
#data1.drop['docName',inplace=True,axis=1]

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1987 entries, 0 to 1986
Data columns (total 64 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   pgNo                 1987 non-null   int64  
 1   startX               1987 non-null   float64
 2   startY               1987 non-null   float64
 3   endX                 1987 non-null   float64
 4   endY                 1987 non-null   float64
 5   w                    1987 non-null   float64
 6   h                    1987 non-null   float64
 7   fntSize              1987 non-null   float64
 8   txtColor             1987 non-null   int64  
 9   pgW                  1987 non-null   int64  
 10  pgH                  1987 non-null   int64  
 11  topMargin            1987 non-null   float64
 12  bottomMargin         1987 non-null   float64
 13  leftMargin           1987 non-null   float64
 14  rightMargin          1987 non-null   float64
 15  lSize                1987 non-null   i

In [28]:
#from sklearn.compose import ColumnTransformer
#from sklearn.preprocessing import OneHotEncoder
#ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [9])], remainder='passthrough')
#X = np.array(ct.fit_transform(X))

In [29]:
data.shape

(1987, 64)

In [30]:
test_data.shape

(621, 63)

In [31]:
#data2=data1.iloc[:, :-1].values


In [32]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [33]:
X_train.shape

(1589, 63)

In [34]:
X_test.shape

(398, 63)

In [35]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
data2_test=sc.transform(test_data)#only scaling


#from sklearn.preprocessing import StandardScaler
#sc = StandardScaler()
##X_train = sc.fit_transform(data)
#X_test = sc.transform(data2)

In [36]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
y

array([4, 4, 4, ..., 5, 5, 5])

In [37]:
#pipeline_lr=Pipeline([('scalar1',StandardScaler()),
 #                    ('pca1',PCA(n_components=2)),
  #                   ('lr_classifier',LogisticRegression(random_state=0))])

In [38]:
#pipeline_dt=Pipeline([('scalar2',StandardScaler()),
 #                    ('pca2',PCA(n_components=2)),
  #                   ('dt_classifier',DecisionTreeClassifier())])


In [39]:
#pipeline_randomforest=Pipeline([('scalar3',StandardScaler()),
 #                    ('pca3',PCA(n_components=2)),
  #                   ('rf_classifier',RandomForestClassifier())])

In [40]:
#pipeline_sv=Pipeline([('scalar4',StandardScaler()),
 #                    ('pca4',PCA(n_components=2)),
  #                   ('sv_classifier',SVC())])


In [41]:
#pipeline_xg=Pipeline([('scalar5',StandardScaler()),
 #                    ('pca5',PCA(n_components=2)),
  #                   ('xg_classifier',XGBClassifier())])


In [42]:
#pipelines = [pipeline_lr, pipeline_dt, pipeline_randomforest,pipeline_sv,pipeline_xg]

In [43]:
#best_accuracy=0.0
#best_classifier=0
#best_pipeline=""

In [44]:
#pipe_dict = {0: 'Logistic Regression', 1: 'Decision Tree', 2: 'RandomForest',3:'SVM',4:'xgboost'}

# Fit the pipelines
#for pipe in pipelines:
#	pipe.fit(X_train, y_train)

In [45]:
#for i,model in enumerate(pipelines):
 #   print("{} Test Accuracy: {}".format(pipe_dict[i],model.score(X_test,y_test)))

In [46]:
#for i,model in enumerate(pipelines):
 #   if model.score(X_test,y_test)>best_accuracy:
  #      best_accuracy=model.score(X_test,y_test)
   #     best_pipeline=model
    #    best_classifier=i
#print('Classifier with best accuracy:{}'.format(pipe_dict[best_classifier]))

In [47]:
#from sklearn.metrics import confusion_matrix, accuracy_score
#y_pred = classifier.predict(X_test)
#cm = confusion_matrix(y_test, y_pred)
#print(cm)
#accuracy_score(y_test, y_pred)

In [48]:
#from sklearn.model_selection import GridSearchCV
#clf=GridSearchCv()



In [49]:
# Create a pipeline
#pipe = Pipeline([("classifier", RandomForestClassifier())])
# Create dictionary with candidate learning algorithms and their hyperparameters
#grid_param = [
 #               "classifier__penalty": ['l2','l1'],
  #               "classifier__C": np.logspace(0, 4, 10)
   #              },
    #            {"classifier": [LogisticRegression()],
     #            "classifier__penalty": ['l2'],
      #           "classifier__C": np.logspace(0, 4, 10),
       #          "classifier__solver":['newton-cg','saga','sag','liblinear'] ##This solvers don't allow L1 penalty
        #         },
         #       {"classifier": [RandomForestClassifier()],
          #       "classifier__n_estimators": [10, 100, 1000],
           #      "classifier__max_depth":[5,8,15,25,30,None],
            #     "classifier__min_samples_leaf":[1,2,5,10,15,100],
             #    "classifier__max_leaf_nodes": [2, 5,10]},
                
#]
# create a gridsearch of the pipeline, the fit the best model
#gridsearch = GridSearchCV(pipe, grid_param, cv=5, verbose=0,n_jobs=-1) # Fit grid search
#best_model = gridsearch.fit(X_train,y_train)


In [50]:
#print(best_model.best_estimator_)
#print("The mean accuracy of the model is:",best_model.score(X_test,y_test))

In [51]:
#from sklearn.linear_model import LogisticRegression
#classifier = LogisticRegression(random_state = 0)
#classifier.fit(X_train, y_train)

In [52]:
#from sklearn.tree import DecisionTreeClassifier
#classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
#classifier.fit(X_train, y_train)

In [53]:
#from sklearn.neighbors import KNeighborsClassifier
#classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
#classifier.fit(X_train, y_train)
#99.375

In [54]:
#from sklearn.svm import SVC
#classifier = SVC(kernel = 'rbf', random_state = 0, C=30,gama='auto')
#classifier.fit(X_train, y_train)

In [55]:
X_test.shape

(398, 63)

In [56]:
data2_test.shape

(621, 63)

In [57]:
X_train.shape


(1589, 63)

In [60]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [59]:
from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=0, num_parallel_tree=1,
              objective='multi:softprob', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=None, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [61]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[  1   0   0   0   0   2]
 [  0   0   0   0   0   1]
 [  0   0   2   0   0   1]
 [  0   0   0   0   0   2]
 [  0   0   0   0   6   4]
 [  0   0   0   1   0 378]]


0.9723618090452262

In [62]:
y_pred = classifier.predict(data2_test)
print(y_pred)
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),2))
#X_test

['Name' 'Name' 'Name' 'Name' 'Name' 'Name' 'Name' 'unnamed' 'unnamed'
 'unnamed' 'unnamed' 'unnamed' 'unnamed' 'unnamed' 'unnamed' 'unnamed'
 'unnamed' 'unnamed' 'unnamed' 'unnamed' 'unnamed' 'unnamed' 'unnamed'
 'unnamed' 'unnamed' 'unnamed' 'unnamed' 'unnamed' 'unnamed' 'unnamed'
 'unnamed' 'unnamed' 'unnamed' 'Inv_Num' 'unnamed' 'unnamed' 'unnamed'
 'unnamed' 'unnamed' 'unnamed' 'unnamed' 'unnamed' 'unnamed' 'unnamed'
 'unnamed' 'unnamed' 'Inv_date' 'unnamed' 'unnamed' 'unnamed' 'unnamed'
 'GSTIN' 'unnamed' 'unnamed' 'unnamed' 'unnamed' 'unnamed' 'unnamed'
 'unnamed' 'unnamed' 'unnamed' 'unnamed' 'unnamed' 'unnamed' 'unnamed'
 'unnamed' 'unnamed' 'unnamed' 'unnamed' 'unnamed' 'unnamed' 'unnamed'
 'unnamed' 'unnamed' 'unnamed' 'unnamed' 'unnamed' 'unnamed' 'unnamed'
 'unnamed' 'unnamed' 'unnamed' 'unnamed' 'unnamed' 'unnamed' 'unnamed'
 'unnamed' 'unnamed' 'unnamed' 'unnamed' 'unnamed' 'unnamed' 'unnamed'
 'unnamed' 'unnamed' 'unnamed' 'unnamed' 'unnamed' 'unnamed' 'unnamed'
 'unname